### ISSUE TITLE
Editor - Saving Nissan ROM fails with Error

### ISSUE THREAD

**Issue by dschultzca** [RomRaider/RomRaider#184]
RomRaider version 0.9.1  
https://www.romraider.com/forum/viewtopic.php?f=64&t=19510

**Comment by dschultzca** [comment]
```
java.lang.IllegalArgumentException: 35096 > 4
	at java.util.Arrays.copyOfRange(Arrays.java:3064)
	at com.romraider.maps.checksum.NissanChecksum.update(NissanChecksum.java:82)
	at com.romraider.maps.checksum.ChecksumSTD.update(ChecksumSTD.java:1)
	at com.romraider.maps.Rom.updateChecksum(Rom.java:533)
	at com.romraider.maps.Rom.saveFile(Rom.java:414)
	at com.romraider.swing.ECUEditorMenuBar.saveImage(ECUEditorMenuBar.java:504)
	at com.romraider.swing.ECUEditorMenuBar.actionPerformed(ECUEditorMenuBar.java:353)

```
